### ISSUE TITLE
feat: basic cli command

### ISSUE THREAD

**Issue by gioboa** [QwikDev/RoadPlan#2]
> Let's start with a basic implementation and than we can iterate on it.

I would like to release this project as a npm package usable with the npm cli 
e.g. `npx roadplan@latest`

So these are the steps
- ask for favourite npm package manager (npm, yarn, pnpm, bun) and use it in the next steps
- ask for project name
- create a folder with that name
- copy all the roadplan repository files into it (without internal files / folders)
- install dependencies 

[This article](https://hackernoon.com/publishing-a-nodejs-cli-tool-to-npm-in-less-than-15-minutes ) could be an help but you can find a lot of article for this topic.

**Comment by pietrodev07** [comment]
Hi, I'd like to take care of it

**Comment by pietrodev07** [comment]
Hello everyone, what is your favourite npm package manager?

**Comment by gioboa** [comment]
> Hello everyone, what is your favourite npm package manager?

pnpm

**Comment by pietrodev07** [comment]
What name would you give to the project?
