### ISSUE TITLE
How can I contribute to RoadPlan and what's it about?

### ISSUE THREAD

**Issue by rishi-raj-jain** [QwikDev/RoadPlan#4]

**Comment by gioboa** [comment]
This project is a complete starter for quickly and easily creating your documentation site with Qwik. I'm working at the CLI and I will publish the first release soon.
Then I will open some issues to track the missing features. I'm glad that you want collaborate in the project

**Comment by rishi-raj-jain** [comment]
Oh that's great! I'm stoked to try this out. I've used starlight.astro.build before.

**Comment by rishi-raj-jain** [comment]
> Then I will open some issues to track the missing features. I'm glad that you want collaborate in the project

For sure, I've already contributed to the qwikdev/astro package, and would love to do it here as well :D
