### ISSUE TITLE
CLI: support `yarn create` & `pnpm exec`

### ISSUE THREAD

**Issue by gioboa** [QwikDev/RoadPlan#5]
`npx` command allows you to run an arbitrary command from an npm package (either one installed locally, or fetched remotely), in a similar context as running it via npm run. 
[Full docs here](https://docs.npmjs.com/cli/v8/commands/npx)

`npx @qwikdev/roadplan` and `bunx @qwikdev/roadplan` are working fine.

we need to support other package manager too.
```shell
pnpm exec @qwikdev/roadplan
yarn create @qwikdev/roadplan
```

**Comment by VarPDev** [comment]
I would like to try to work on it

**Comment by VarPDev** [comment]
Commands will be:

pnpm create roadplan
yarn create roadplan
npm create roadplan
bun create roadplan

**Comment by gioboa** [comment]
Closed by #7
